#!/bin/bash

# This script extracts a private key and a public certificate from a PKCS#12 file
# generated by the Quarkus CLI, and places them in a target directory.

# --- Configuration ---
# The path to the .p12 file generated by Quarkus.
# This keystore contains both the private key and the public certificate.
P12_KEYSTORE_FILE=".certs/flipt-cert-keystore.p12"

# The password for the input .p12 file.
P12_PASSWORD="password"

# The target directory where the extracted .key and .crt files will be saved.
OUTPUT_DIR="src/test/resources"

set -e

if [ ! -f "$P12_KEYSTORE_FILE" ]; then
    echo "Error: Input file not found at '$P12_KEYSTORE_FILE'"
    echo "Please generate the certificate first using: quarkus tls generate-certificate --name flipt-cert --self-signed --password=password"
    exit 1
fi

echo "Ensuring output directory exists: $OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

echo "Extracting private key to $OUTPUT_DIR/server.key..."
openssl pkcs12 \
  -in "$P12_KEYSTORE_FILE" \
  -nocerts \
  -nodes \
  -out "$OUTPUT_DIR/server.key" \
  -passin pass:"$P12_PASSWORD"

echo "Adding read permissions to $OUTPUT_DIR/server.key..."
chmod a+r "$OUTPUT_DIR/server.key"

echo "Extracting public certificate to $OUTPUT_DIR/server.crt..."
openssl pkcs12 \
  -in "$P12_KEYSTORE_FILE" \
  -nokeys \
  -clcerts \
  -out "$OUTPUT_DIR/server.crt" \
  -passin pass:"$P12_PASSWORD"

echo "Adding read permissions to $OUTPUT_DIR/server.crt..."
chmod a+r "$OUTPUT_DIR/server.crt"

echo ""
echo "✅ Success! server.key and server.crt have been extracted to $OUTPUT_DIR"
